### PR TITLE
Fix #340

### LINKED ISSUE #340: Identifiable ResourceReloadListener and ordering
~~Thank you GitHub for wrongly submitting the issue early
So, hopefully I can write quickly enough before anyone sees this incomplete issue.~~

Architectury API allows to register resource reload listeners via [ReloadListenerRegistry](https://github.com/architectury/architectury-api/blob/6a9d61aa425fec0ea24be8a56b14b9340f23cf55/common/src/main/java/dev/architectury/registry/ReloadListenerRegistry.java#L31). This is neat up until you see the Fabric/Quilt's take on the system.

In the Fabric and Quilt ecosystem those reloaders are named and have stable identifiers, this is important as it allows other reloaders to re-order them (depend or make sure to run before, etc).
This can be very important in the case of addon mods, and others.

This expectation is entirely wrecked with Architectury API not letting mods name their reloaders and giving them random IDs.
In addition, it doesn't let anyone re-order reloaders, which led to some people trying to order using registration call order (and that is entirely wrecked by Quilt's own reloader sorter since it's not using Lists but HashMaps).

It would be nice to add a way to give stable names and specify dependencies on resource reloaders inside of Architectury API to satisfy Fabric and Quilt's expectations.

### PR DESCRIPTION
**Pull request by shedaniel**
ReloadListenerRegistry now with optional RSLoc argument and dependencies argument, we are not going to sort the dependencies on Forge, that's too much of a headache.

### CODE REVIEW

File: common/src/main/java/dev/architectury/registry/ReloadListenerRegistry.java [hunk 1]
```diff
@@ -20,15 +20,28 @@
 package dev.architectury.registry;
 
 import dev.architectury.injectables.annotations.ExpectPlatform;
+import net.minecraft.resources.ResourceLocation;
 import net.minecraft.server.packs.PackType;
 import net.minecraft.server.packs.resources.PreparableReloadListener;
 
+import javax.annotation.Nullable;
```
Comment (Juuxel) [inline common/src/main/java/dev/architectury/registry/ReloadListenerRegistry.java:27]: Do we use javax nullable?

Comment (MaxNeedsSnacks) [reply common/src/main/java/dev/architectury/registry/ReloadListenerRegistry.java:27]: We do not, please switch to jbr annotations if possible

Comment (MaxNeedsSnacks) [reply common/src/main/java/dev/architectury/registry/ReloadListenerRegistry.java:27]: Gonna fix this in an extra PR after this one actually, since we do seem to be using javax in some other places where we shouldn't

**Review by MaxNeedsSnacks — APPROVED** [review]
Side note: IMO users should always supply an ID for their reload listeners for proper ordering on Fabriquilt, so maybe we should deprecate the method without the `listenerId` parameter for removal in a future version of the API (as well as not mark the parameter as explicitly nullable if that deprecation is introduced)

I'm happy to merge this in its current state, however, as it is more important that we *get this fixed* than to have the API laid out perfectly, and this has been dormant for too long anyways :P
