### PR TITLE
Fixed EntitySpawnExtension buffer being unable to be read from, #208

### LINKED ISSUE #208: EntitySpawnExtension causes IllegalReferenceCountException on Fabric client
When using the EntitySpawnExtension we're running into an IllegalReferenceCountException on the Fabric client.

The code we're using can be found here: https://gitlab.com/cable-mc/pokemon-cobbled/-/blob/41e4a88c389bf76871b9c54fbc536129b9313702/common/src/main/kotlin/com/cablemc/pokemoncobbled/common/entity/pokemon/PokemonEntity.kt

And the stacktrace is:
```
[07:25:46] [Render thread/FATAL] (Minecraft) Error executing task on Client
 io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1440) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at net.minecraft.network.FriendlyByteBuf.readFloat(FriendlyByteBuf.java:1042) ~[minecraft-project-@fabric-mapped.jar:?]
	at com.cablemc.pokemoncobbled.common.entity.pokemon.PokemonEntity.loadAdditionalSpawnData(PokemonEntity.java:209) ~[2953412868271822787.jar:?]
	at dev.architectury.networking.fabric.SpawnEntityPacket$Client.lambda$receive$0(SpawnEntityPacket.java:106) ~[architectury-fabric-3.7.22.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:146) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:29) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:116) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:932) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:641) [minecraft-project-@fabric-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:212) [minecraft-project-@fabric-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217) [architectury-transformer-5.2.61-runtime.jar:5.2.61]
```

### PR DESCRIPTION
**Pull request by Hiroku**
The buffer exception mentioned in #208 suggests that the buffer used for the packet is marked as having no further references for garbage collection by the time the context block executes. The solution is to evacuate the remaining bytes from the buffer while the reference is held and letting this new buffer be consumed in the context block.

Closes #208

### CODE REVIEW

File: fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java [hunk 1]
```diff
@@ -103,7 +105,7 @@ public static void receive(FriendlyByteBuf buf, NetworkManager.PacketContext con
                 entity.setYHeadRot(yHeadRot);
                 entity.setYBodyRot(yHeadRot);
                 if (entity instanceof EntitySpawnExtension ext) {
-                    ext.loadAdditionalSpawnData(buf);
+                    ext.loadAdditionalSpawnData(extBuf);
```
Comment (shedaniel) [inline fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java]: Might need to close the new buffer here then?

**Review by shedaniel — CHANGES_REQUESTED** [review]

File: fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java (hunk 1 above)
Comment (Hiroku) [reply fabric/src/main/java/dev/architectury/networking/fabric/SpawnEntityPacket.java]: Good point, done in [3a687df](https://github.com/architectury/architectury-api/pull/220/commits/3a687dffd469db49ed5f39598cdcba40ef02e9b7)

**Review by shedaniel — APPROVED** [review]
LGTM, Thanks! Will merge later

**Comment by Juuxel** [comment]
I think you can also hold the original buffer with `buf.retain()` (see [fabric api](https://github.com/FabricMC/fabric/blob/08b1b79b17d800aed105d8eba85a270a0876d355/fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/client/ClientNetworking.java#L52) for example) and then release it after you're done with `buf.release()` like the copy, but copying should work too.

**Comment by Hiroku** [comment]
> I think you can also hold the original buffer with `buf.retain()` (see [fabric api](https://github.com/FabricMC/fabric/blob/08b1b79b17d800aed105d8eba85a270a0876d355/fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/client/ClientNetworking.java#L52) for example) and then release it after you're done with `buf.release()` like the copy, but copying should work too.

I'll remember that, though I can change it over if shedaniel likes. Just means re-reviewing.

**Comment by shedaniel** [comment]
Re-reviewing is fine! Please do :p

**Comment by Hiroku** [comment]
No worries, updated.

~~Also looks like it doesn't require a re-review, I'm too used to other environments!~~ Or you're just really fast

**Review by shedaniel — APPROVED** [review]

**Review by MaxNeedsSnacks — APPROVED** [review]
