### PR TITLE
Backported fluid stack fix to 1.20.2

### LINKED ISSUE #484: NeoForge 1.20.2 Holder does not implement Supplier, resulting in FluidStack crash.
In NeoForge 20.2.59-beta `Supplier` was removed from `net.minecraft.core.Holder`

Commit: https://github.com/neoforged/NeoForge/pull/257/commits/ed1b47716277689ddaa4d0743b8cf81011922eb3

This is the patch that was removed:
https://github.com/neoforged/NeoForge/blob/1ba480f54685088db109e719081d23fb5bc3848e/patches/net/minecraft/core/Holder.java.patch

As a result, FluidStack creation via `FluidStack#create(FluidStack, long)` crashes with:
`java.lang.IncompatibleClassChangeError: Class net.minecraft.core.Holder$Reference does not implement the requested interface java.util.function.Supplier`
Full Crash: https://ss.brandon3055.com/ebe85

### PR DESCRIPTION
**Pull request by Jab125**
fix: FluidStackImpl#getRawFluidSupplier crashing on forge/neoforge

### CODE REVIEW

File: forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ public FluidStack create(Supplier<Fluid> fluid, long amount, CompoundTag tag) {
     
     @Override
     public Supplier<Fluid> getRawFluidSupplier(FluidStack object) {
-        return BuiltInRegistries.FLUID.getHolderOrThrow(BuiltInRegistries.FLUID.getResourceKey(object.getRawFluid()).orElseThrow());
+        return () -> BuiltInRegistries.FLUID.getHolderOrThrow(BuiltInRegistries.FLUID.getResourceKey(object.getRawFluid()).orElseThrow()).value();
```
Comment (shedaniel) [inline forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java:57]: Maybe use a method ref here

**Review by shedaniel — CHANGES_REQUESTED** [review]

File: forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java (hunk 1 above)
Comment (Jab125) [reply forge/src/main/java/dev/architectury/fluid/forge/FluidStackImpl.java:57]: It's a direct cherry pick of #483 to 1.20.2

**Review by shedaniel — APPROVED** [review]
